### ISSUE TITLE
Add Icons to footer tab

### ISSUE THREAD

**Issue by kanielv** [ufosc/Alarm-Clock#39]
The footer tab needs some icons. I'll leave the choice of Icons to you but make sure they match with the tab name.

Refer to https://www.npmjs.com/package/react-native-vector-icons to get the icons.

**Comment by cpwallah** [comment]
@kanielv i can do this

**Comment by MaximilianMeiler** [comment]
> @kanielv i can do this

Go right ahead!

**Comment by kanielv** [comment]
> > @kanielv i can do this
> 
> Go right ahead!

Someone else was already working on this one yesterday.  I forgot to update the issue that's my bad.

**Comment by MaximilianMeiler** [comment]
💀

**Comment by cpwallah** [comment]
ohh no i have solve the error
