### ISSUE TITLE
Move add alarm feature to Alarms Tab

### ISSUE THREAD

**Issue by kanielv** [ufosc/Alarm-Clock#47]
The last pull request placed the add alarms where the clock tab is placed. We need someone to move the add alarm functionality to the alarm tab while maintaining functionality.

**Comment by cpwallah** [comment]
hi @kanielv i can do this

**Comment by kanielv** [comment]
I believe @MaximilianMeiler is already working on this. My bad for not assigning him earlier.

**Comment by MaximilianMeiler** [comment]
My bad for not making the PR earlier :P
