### ISSUE TITLE
Add delete confirmation modal for world clock tab.

### ISSUE THREAD

**Issue by kanielv** [ufosc/Alarm-Clock#62]
Add a modal asking the user to confirm that they want to delete a Clock object from the Clock tab after the user clicks delete.

 <img src="https://github.com/user-attachments/assets/05c2b12b-5732-4a12-823a-f18ce9b494f5" width="200">

It should look something similar to this example below. You can find and use this code as an example to help you. 

 <img src="https://github.com/user-attachments/assets/725f651c-e50e-4200-8747-27e048f99ea4" width="200">

**Comment by kanielv** [comment]
I assigned you this issue. Good luck!

**Comment by Rushilkothur** [comment]
I pushed the feature yesterday, seems to be fully functional.
