### ISSUE TITLE
Update README to reflect backend changes

### ISSUE THREAD

**Issue by kanielv** [ufosc/Alarm-Clock#92]
The new main file is located in cmd/app. Update the readme to reflect these changes.

**Comment by rexept** [comment]
Hey! May I be assigned this issue?

Also just to confirm, is **server.go** now **main.go** after the refactor (which is located in **cmd/app**)?

**Comment by kanielv** [comment]
Go for it! And yes,, server.go is now main.go in the cmd/app.

**Comment by rexept** [comment]
You can ignore the first reference because I accidentally PRed to my own fork. This is my first time submitting a PR on a phone lol.

**Comment by kanielv** [comment]
This is completed
